In [16]:
#from sklearn.model_selection import KFold
from sklearn import model_selection
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np
import pickle

In [17]:
dataset = pd.read_csv('data.csv', header = None)

In [18]:
print(dataset.head())

                   0                       1                  2   \
0  Programming skills  Problem solving skills  Analytical skills   
1        Professional          Not Interested     Not Interested   
2        Professional                    Poor     Not Interested   
3        Professional                Beginner     Not Interested   
4        Professional                 Average     Not Interested   

               3                   4                     5               6   \
0  Logical skills  Statistical skills  Communication skills         Styling   
1  Not Interested      Not Interested        Not Interested  Not Interested   
2  Not Interested      Not Interested        Not Interested  Not Interested   
3  Not Interested      Not Interested        Not Interested  Not Interested   
4  Not Interested      Not Interested        Not Interested  Not Interested   

                  7                      8                   9   \
0  Creativity skills  Organisational skills  Nego

In [19]:
dataset.columns= ["Programming skills","Problem solving skills","Analytical skills","Logical skills","Statistical skills","Communication skills","Styling","Creativity skills","Organisational skills","Negotiation skills","Attention to details","Empathy","Leadership","Stress management","Listening skills","Research","Emotional intelligence","Role"]
dataset.dropna(how ='all', inplace = True)

In [20]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [21]:
df = pd.DataFrame(dataset)
le = LabelEncoder()
df['Programming skills'] = le.fit_transform(df['Programming skills'])
df['Problem solving skills'] = le.fit_transform(df['Problem solving skills'])
df['Analytical skills'] = le.fit_transform(df['Analytical skills'])
df['Logical skills'] = le.fit_transform(df['Logical skills'])
df['Statistical skills'] = le.fit_transform(df['Statistical skills'])
df['Communication skills'] = le.fit_transform(df['Communication skills'])
df['Styling'] = le.fit_transform(df['Styling'])
df['Creativity skills'] = le.fit_transform(df['Creativity skills'])
df['Organisational skills'] = le.fit_transform(df['Organisational skills'])
df['Negotiation skills'] = le.fit_transform(df['Negotiation skills'])
df['Attention to details'] = le.fit_transform(df['Attention to details'])
df['Empathy'] = le.fit_transform(df['Empathy'])
df['Leadership'] = le.fit_transform(df['Leadership'])
df['Stress management'] = le.fit_transform(df['Stress management'])
df['Listening skills'] = le.fit_transform(df['Listening skills'])
df['Research'] = le.fit_transform(df['Research'])
df['Emotional intelligence'] = le.fit_transform(df['Emotional intelligence'])
df.head()

Programming skills  Problem solving skills  Analytical skills  \
0                   7                       6                  0   
1                   6                       4                  5   
2                   6                       5                  5   
3                   6                       1                  5   
4                   6                       0                  5   

   Logical skills  Statistical skills  Communication skills  Styling  \
0               4                   7                     2        7   
1               5                   4                     5        4   
2               5                   4                     5        4   
3               5                   4                     5        4   
4               5                   4                     5        4   

   Creativity skills  Organisational skills  Negotiation skills  \
0                  2                      5                   4   
1                  5                      4                   5   
2                  5                      4                   5   
3                  5                      4                   5   
4                  5                      4                   5   

   Attention to details  Empathy  Leadership  Stress management  \
0                     0        2           4                  7   
1                     5        5           5                  4   
2                     5        5           5                  4   
3                     5        5           5                  4   
4                     5        5           5                  4   

   Listening skills  Research  Emotional intelligence      Role  
0                 4         7                       2      Role  
1                 5         4                       5  Engineer  
2                 5         4                       5  Engineer  
3                 5         4                       5  Engineer  
4                 5         4                       5  Engineer

In [22]:
X=np.array(dataset.iloc[:, 0:17]) 
print(X)
Y = np.array(dataset.iloc[:, 17])
print(Y)

[[7 6 0 ... 4 7 2]
 [6 4 5 ... 5 4 5]
 [6 5 5 ... 5 4 5]
 ...
 [4 4 5 ... 0 0 7]
 [4 4 5 ... 3 3 7]
 [4 4 5 ... 2 2 7]]
['Role' 'Engineer' 'Engineer' ... 'Pilot' 'Pilot' 'Pilot']


In [24]:
seed=5
kfold = model_selection.KFold(n_splits = 15,
                       shuffle=True)
#kfold = KFold(n_splits = 15, shuffle= True)

In [25]:
base_cls = DecisionTreeClassifier()

In [26]:
num_trees = 50

In [29]:
model = BaggingClassifier(base_estimator = base_cls,
                          n_estimators = num_trees,
                          random_state = 5)

In [30]:
results = model_selection.cross_val_score(model, X, Y, cv = kfold)
print("accuracy :",results.mean()*100)

c:\Users\SP. Narayanan\Documents\career dendogram\dendpy\.venv\Lib\site-packages\sklearn\ensemble\_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
c:\Users\SP. Narayanan\Documents\career dendogram\dendpy\.venv\Lib\site-packages\sklearn\ensemble\_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
c:\Users\SP. Narayanan\Documents\career dendogram\dendpy\.venv\Lib\site-packages\sklearn\ensemble\_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
c:\Users\SP. Narayanan\Documents\career dendogram\dendpy\.venv\Lib\site-packages\sklearn\ensemble\_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
c:\Users\SP. Narayanan\Documents\career dendogram\dendpy\.venv\Lib\site-pack

accuracy : 99.81481481481481
